# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisGui(object):
    def setupUi(self, JarvisGui):
        JarvisGui.setObjectName("JarvisGui")
        JarvisGui.resize(1410, 869)
        self.centralwidget = QtWidgets.QWidget(JarvisGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 100, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, -160, 1741, 1181))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/ironan.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1050, 790, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 790, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 20, 411, 121))
        self.label_3.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/ironman2.gif"))
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(670, 40, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius: none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(990, 40, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1090, 620, 271, 201))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        JarvisGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JarvisGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1410, 26))
        self.menubar.setObjectName("menubar")
        JarvisGui.setMenuBar(self.menubar)

        self.retranslateUi(JarvisGui)
        QtCore.QMetaObject.connectSlotsByName(JarvisGui)

    def retranslateUi(self, JarvisGui):
        _translate = QtCore.QCoreApplication.translate
        JarvisGui.setWindowTitle(_translate("JarvisGui", "MainWindow"))
        self.label.setText(_translate("JarvisGui", "TextLabel"))
        self.pushButton.setText(_translate("JarvisGui", "Run"))
        self.pushButton_2.setText(_translate("JarvisGui", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisGui = QtWidgets.QMainWindow()
    ui = Ui_JarvisGui()
    ui.setupUi(JarvisGui)
    JarvisGui.show()
    sys.exit(app.exec_())
